import "./globals.scss";
import type { Metadata } from "next";
import localfont from "next/font/local";

const myFont = localfont({
  src: [
    { path: "../fonts/GeneralSans-Bold.woff2" },
    { path: "../fonts/GeneralSans-Regular.woff2" },
    { path: "../fonts/GeneralSans-BoldItalic.woff2" },
    { path: "../fonts/GeneralSans-Extralight.woff2" },
    { path: "../fonts/GeneralSans-Regular.woff2" },
    { path: "../fonts/GeneralSans-Light.woff2" },
    { path: "../fonts/GeneralSans-Medium.woff2" },
    { path: "../fonts/GeneralSans-Semibold.woff2" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
